module.exports = {
  productionFiles: [
    'Config.gs', 'IConfigRepository.gs', 'IContestSource.gs', 'ICriteriaRepository.gs',
    'IDashboardRepository.gs', 'IHistoryRepository.gs', 'ILogRepository.gs',
    'IStatisticsEngine.gs', 'IStatisticsRepository.gs', 'HistoryIntegrity.gs',
    'HistoryIntegrityReport.gs', 'Contest.gs', 'NumberAnalysis.gs', 'Statistic.gs',
    'SyndicateLotteryGame.gs', 'SyndicateLotteryGameResult.gs', 'FrequencyWindow.gs',
    'ContestDTO.gs', 'StatisticDTO.gs', 'StatisticsEngine.gs', 'CaixaMegaSenaContestSource.gs',
    'HttpClient.gs', 'PipelineContext.gs', 'PipelineEngine.gs', 'PipelineLogger.gs',
    'PipelineResult.gs', 'PipelineStep.gs', 'IRankingStrategy.gs', 'RankingEngine.gs',
    'RankingResult.gs', 'ScoreRankingStrategy.gs', 'ConfigRepository.gs', 'CriteriaRepository.gs',
    'DashboardRepository.gs', 'HistoryRepository.gs', 'InMemoryStatisticsRepository.gs',
    'LogRepository.gs', 'StatisticsRepository.gs', 'SyndicateGamesSheetRepository.gs',
    'IScoreCalculator.gs', 'ScoreBreakdown.gs', 'ScoreEngine.gs', 'ScoreResult.gs',
    'WeightedScoreCalculator.gs', 'ISelectionStrategy.gs', 'SelectionEngine.gs',
    'SelectionResult.gs', 'TopSelectionStrategy.gs', 'CriteriaService.gs', 'DashboardService.gs',
    'HistorySyncService.gs', 'HistoryValidationService.gs', 'PipelineService.gs',
    'RankingService.gs', 'ScoreService.gs', 'SelectionService.gs', 'StatisticsService.gs',
    'SyndicateGamesSheetService.gs', 'SyndicateLotteryResult.gs', 'SyndicateLotteryService.gs',
    'DateNormalizer.gs', 'Menu.gs'
  ],
  testFiles: [
    'ConfigRepository.test.gs', 'HistorySyncService.test.gs', 'HistorySyncEngine.test.gs',
    'CaixaMegaSenaContestSource.test.gs', 'DateNormalizer.test.gs', 'HistoryIntegrity.test.gs',
    'HistoryRepository.test.gs', 'StatisticsEngine.test.gs', 'CriteriaEngine.test.gs',
    'ScoreEngine.test.gs', 'RankingSelectionEngine.test.gs', 'HistorySyncMenu.test.gs',
    'SyndicateLotteryMenu.test.gs', 'SyndicateGamesSheetRepository.test.gs',
    'SyndicateGamesSheetService.test.gs', 'HistoryValidationService.test.gs',
    'InMemoryStatisticsRepository.test.gs', 'BacktestEngine.test.gs', 'BaselineBacktest.test.gs',
    'BaselineTopDiagnosis.test.gs', 'RankingDiagnosis.test.gs', 'RandomBaselineBacktest.test.gs',
    'SyndicateConfig.test.gs', 'NewScoreStrategy.test.gs', 'NewScoreCalculator.test.gs',
    'NewScoreStrategyBacktest.test.gs', 'AblationBacktest.test.gs', 'SyndicateLotteryService.test.gs',
    'PipelineEngine.test.gs', 'AnalyticsPipelineMemory.test.gs'
  ],
  runners: [
    { name: 'runConfigRepositoryTests', file: 'tests/unit/ConfigRepository.test.gs', cases: ['test'] },
    { name: 'runHistorySyncServiceTests', file: 'tests/unit/HistorySyncService.test.gs', cases: ['test'] },
    { name: 'runHistorySyncEngineTests', file: 'tests/unit/HistorySyncEngine.test.gs', cases: ['test'] },
    { name: 'runCaixaMegaSenaContestSourceTests', file: 'tests/unit/CaixaMegaSenaContestSource.test.gs', cases: ['test'] },
    { name: 'runDateNormalizerTests', file: 'tests/unit/DateNormalizer.test.gs', cases: ['test'] },
    { name: 'runHistoryIntegrityTests', file: 'tests/unit/HistoryIntegrity.test.gs', cases: ['test'] },
    { name: 'runHistoryRepositoryTests', file: 'tests/unit/HistoryRepository.test.gs', cases: ['test'] },
    { name: 'runStatisticsEngineTests', file: 'tests/unit/StatisticsEngine.test.gs', cases: ['test'] },
    { name: 'runCriteriaEngineTests', file: 'tests/unit/CriteriaEngine.test.gs', cases: ['test'] },
    { name: 'runScoreEngineTests', file: 'tests/unit/ScoreEngine.test.gs', cases: ['test'] },
    { name: 'runRankingSelectionEngineTests', file: 'tests/unit/RankingSelectionEngine.test.gs', cases: ['test'] },
    { name: 'runHistorySyncMenuTests', file: 'tests/unit/HistorySyncMenu.test.gs', cases: ['test'] },
    { name: 'runSyndicateLotteryMenuTests', file: 'tests/unit/SyndicateLotteryMenu.test.gs', cases: ['test'] },
    { name: 'runSyndicateGamesSheetRepositoryTests', file: 'tests/unit/SyndicateGamesSheetRepository.test.gs', cases: ['find sheet', 'insert single', 'get by contest', 'has games'] },
    { name: 'runSyndicateGamesSheetServiceTests', file: 'tests/unit/SyndicateGamesSheetService.test.gs', cases: ['persist games', 'skip existing', 'calculate target', 'extract numbers'] },
    { name: 'runHistoryValidationServiceTests', file: 'tests/unit/HistoryValidationService.test.gs', cases: ['test'] },
    { name: 'runInMemoryStatisticsRepositoryTests', file: 'tests/unit/InMemoryStatisticsRepository.test.gs', cases: ['test'] },
    { name: 'runBacktestEngineTests', file: 'tests/unit/BacktestEngine.test.gs', cases: ['test'] },
    { name: 'runBaselineBacktestTests', file: 'tests/unit/BaselineBacktest.test.gs', cases: ['test'] },
    { name: 'runBaselineTopDiagnosisTests', file: 'tests/unit/BaselineTopDiagnosis.test.gs', cases: ['test'] },
    { name: 'runRankingDiagnosisTests', file: 'tests/unit/RankingDiagnosis.test.gs', cases: ['test'] },
    { name: 'runRandomBaselineBacktestTests', file: 'tests/unit/RandomBaselineBacktest.test.gs', cases: ['test'] },
    { name: 'runSyndicateConfigTests', file: 'tests/unit/SyndicateConfig.test.gs', cases: ['test'] },
    { name: 'runNewScoreStrategyTests', file: 'tests/unit/NewScoreStrategy.test.gs', cases: ['test'] },
    { name: 'runNewScoreCalculatorTests', file: 'tests/unit/NewScoreCalculator.test.gs', cases: ['test'] },
    { name: 'runNewScoreStrategyBacktestTests', file: 'tests/unit/NewScoreStrategyBacktest.test.gs', cases: ['test'] },
    { name: 'runAblationBacktestTests', file: 'tests/unit/AblationBacktest.test.gs', cases: ['test'] },
    { name: 'runSyndicateLotteryServiceTests', file: 'tests/unit/SyndicateLotteryService.test.gs', cases: ['test'] },
    { name: 'runPipelineEngineIntegrationTests', file: 'tests/integration/PipelineEngine.test.gs', cases: ['test'] },
    { name: 'runAnalyticsPipelineMemoryTests', file: 'tests/integration/AnalyticsPipelineMemory.test.gs', cases: ['test'] }
  ]
};
